version: '3.7'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

  app:
    image: todo-front-dev
    build:
      context: ./todo-frontend
      dockerfile: ./todo-frontend/dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
    container_name: todo-front-dev

  server:
      image: todo-backend-dev
      build:
        context: ./todo-backend
        dockerfile: ./todo-backend/dev.Dockerfile
      volumes:
        - ./todo-backend:/usr/src/app
      ports:
        - 4000:4000 
      environment:
          - REDIS_URL=redis://todo-backend-redis:6379
          - MONGO_URL=mongodb://the_username:the_password@todo-backend-mongo:27017/the_database
      container_name: todo-backend-dev

  mongo:
      image: mongo
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: the_database
      volumes:
          - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      container_name: todo-backend-mongo

  redis:
      image: redis
      command: ['redis-server', '--appendonly', 'yes']
      volumes:
          - ./todo-backend/redis_data:/data
      container_name: todo-backend-redis

  debug-helper:
      image: busybox