version: '3.7'

services:
    server:
        image: todo-backend-dev
        volumes:
            - ./:/usr/src/app
        ports:
            - 3000:3000
        environment:
            - REDIS_URL=redis://todo-backend-redis:6379
            - MONGO_URL=mongodb://the_username:the_password@todo-backend-mongo:27017/the_database
        container_name: todo-backend-dev
    mongo:
        image: mongo
        ports:
            - 3456:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: the_database
        volumes:
            - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        container_name: todo-backend-mongo
    redis:
        image: redis
        ports:
            - 6378:6379
        command: ['redis-server', '--appendonly', 'yes']
        volumes:
            - ./redis_data:/data
        container_name: todo-backend-redis
    debug-helper:
        image: busybox
