version: '3.7'
services:
  app:
    image: todo-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3030:3000
    container_name: todo-front-dev